apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: vote-deployment-aws-secrets
spec:
    provider: aws
    secretObjects:
        -   secretName: votesecretuser
            type: Opaque
            data:
            -   objectName: PostgresUser                    # name of the mounted content to sync. this could be the object name or object alias
                key: username
            -   objectName: PostgresPassword                    # name of the mounted content to sync. this could be the object name or object alias
                key: password
    parameters:
        objects: |
            - objectName: "PostgresUser"
              objectType: "secretsmanager"
            - objectName: "PostgresPassword"
              objectType: "secretsmanager"